// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arena-vibes/StarkLight.tsx": () => import("../components/mockups/arena-vibes/StarkLight.tsx"),
  "./components/mockups/arena-vibes/Terminal.tsx": () => import("../components/mockups/arena-vibes/Terminal.tsx"),
  "./components/mockups/arena-vibes/WarmSlate.tsx": () => import("../components/mockups/arena-vibes/WarmSlate.tsx")
};
